#!/bin/bash

# Desktop environment
sudo apt-get install i3 polybar rofi feh fonts-font-awesome xinput

# Terminal tools
sudo apt-get install alacritty neovim fish

# In the case screen is tearing, check that you use the right graphic card.
# If needed install anc configure compton.

# Setting up Alacrity as default terminal
sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/alacritty 50

# Select default terminal
sudo update-alternatives --config x-terminal-emulator

# Install Fisher
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

# Install languages support for text editor (Helix)

npm install -g vls # Vue

npm install -g dockerfile-language-server-nodejs # Docker

npm i -g vscode-langservers-extracted # Css Html

npm i -g bash-language-server

npm i -g stylelint-lsp

npm install -g typescript-language-server typescript