[[mgr.prepend_keymap]]
on  = "y"
run = [ '''
  shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
''', "yank" ]

[[help.prepend_keymap]]
on  = "/"
run = 'filter'

[[mgr.prepend_keymap]]
on  = "?"
run = 'help'

[[mgr.prepend_keymap]]
on   = [ "g", "/" ]
run  = "cd /"
desc = "Go root"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/workspace/projects"
desc = "Goto Projects"

[[mgr.prepend_keymap]]
on   = [ "g", "a" ]
run  = "cd ~/workspace/apo"
desc = "Goto Apos"

[[mgr.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/Documents"
desc = "Goto ~/Documents"

[[mgr.prepend_keymap]]
on   = [ "g", "D" ]
run  = "cd ~/Downloads"
desc = "Goto ~/Downloads"

[[mgr.prepend_keymap]]
on   = [ "g", "P" ]
run  = "cd ~/Pictures"
desc = "Goto ~/Pictures"


