[[mgr.prepend_keymap]]
on = "y"
run = [
  '''
  shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
''',
  "yank",
]

[[help.prepend_keymap]]
on = "/"
run = 'filter'

[[mgr.prepend_keymap]]
on = "b"
run = 'back'

[[mgr.prepend_keymap]]
on = "H"
run = 'help'

[[mgr.prepend_keymap]]
on = ["g", "/"]
run = "cd /"
desc = "root"

[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/workspace/projects"
desc = "Projects"

[[mgr.prepend_keymap]]
on = ["g", "a"]
run = "cd ~/workspace/apo"
desc = "Apos"

[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Documents"
desc = "Documents"

[[mgr.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/Downloads"
desc = "Downloads"

[[mgr.prepend_keymap]]
on = ["g", "P"]
run = "cd ~/Pictures"
desc = "Pictures"

[[mgr.prepend_keymap]]
on = ["g", "v"]
run = "cd ~/Videos"
desc = "Videos"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
