[opener]
play = [
	{ run = 'vlc "$@"', orphan = true }
]
pdff = [
  { run = 'zathura "$@"', desc = "Zathura", block = true, for = "unix" }
]

[rules]
pdf = [
  { mime = 'application/pdf', use = [ "pdff" ] }
]

[mgr]
show_hidden = false
