#!/usr/bin/env fish

set fish_color_normal D3D7CF
set fish_color_command D3D7CF
set fish_pager_color_prefix D3D7CF
set fish_color_cancel D3D7CF
set tide_pwd_color_anchors D3D7CF
set tide_git_color_untracked D3D7CF

set fish_color_param E3E3E3
set fish_pager_color_completion E3E3E3
set tide_go_color E3E3E3

set fish_color_operator C9282D
set fish_pager_color_description C9282D
set fish_color_cwd C9282D
set fish_color_error C9282D
set fish_color_user C9282D
set tide_character_color_failure C9282D
set tide_git_color_branch C9282D

set fish_color_autosuggestion F0C674
set fish_color_redirection F0C674
set fish_color_quote F0C674
set fish_color_end F0C674
set fish_color_option F0C674
set fish_color_escape F0C674
set tide_character_color F0C674
